base php app image on phusion baseimage

diff --git a/images/app-php/Dockerfile b/images/app-php/Dockerfile
--- a/images/app-php/Dockerfile
+++ b/images/app-php/Dockerfile
@@ -1,15 +1,91 @@
-FROM php:5.6-fpm
+# Use phusion/baseimage as base image. To make your builds
+# reproducible, make sure you lock down to a specific version, not
+# to `latest`! See
+# https://github.com/phusion/baseimage-docker/blob/master/Changelog.md
+# for a list of version numbers.
+FROM phusion/baseimage:0.9.16
 
-ENV LC_ALL=C.UTF-8
+# Use baseimage-docker's init system.
+CMD ["/sbin/my_init"]
 
-RUN \
-  apt-get update \
-  && apt-get install -y --no-install-recommends git libicu52 libpng12-0 libgd3
+# persistent / runtime deps
+RUN apt-get update \
+    && apt-get install -y --no-install-recommends \
+    ca-certificates curl libpcre3 librecode0 libsqlite3-0 libxml2 git libicu52 libpng12-0 libgd3
+
+# phpize deps
+RUN apt-get update \
+    && apt-get install -y --no-install-recommends \
+    autoconf file g++ gcc libc-dev make pkg-config re2c
+
+ENV PHP_INI_DIR /usr/local/etc/php
+RUN mkdir -p $PHP_INI_DIR/conf.d
+
+ENV PHP_EXTRA_CONFIGURE_ARGS --enable-fpm --with-fpm-user=www-data --with-fpm-group=www-data
+
+ENV GPG_KEYS 6E4F6AB321FDC07F2C332E3AC2BF0BC433CFC8B3 0BD78B5F97500D450838F95DFE857D9A90D90EC1
+RUN set -xe \
+	&& for key in $GPG_KEYS; do \
+		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; \
+	done
+
+ENV PHP_VERSION 5.6.9
+
+# --enable-mysqlnd is included below because it's harder to compile after the fact the extensions are (since it's a plugin for several extensions, not an extension in itself)
+RUN buildDeps=" \
+		$PHP_EXTRA_BUILD_DEPS \
+		bzip2 \
+		libcurl4-openssl-dev \
+		libpcre3-dev \
+		libreadline6-dev \
+		librecode-dev \
+		libsqlite3-dev \
+		libssl-dev \
+		libxml2-dev \
+	" \
+	&& set -x \
+	&& apt-get update && apt-get install -y $buildDeps --no-install-recommends && rm -rf /var/lib/apt/lists/* \
+	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2/from/this/mirror" -o php.tar.bz2 \
+	&& curl -SL "http://php.net/get/php-$PHP_VERSION.tar.bz2.asc/from/this/mirror" -o php.tar.bz2.asc \
+	&& gpg --verify php.tar.bz2.asc \
+	&& mkdir -p /usr/src/php \
+	&& tar -xof php.tar.bz2 -C /usr/src/php --strip-components=1 \
+	&& rm php.tar.bz2* \
+	&& cd /usr/src/php \
+	&& ./configure \
+		--with-config-file-path="$PHP_INI_DIR" \
+		--with-config-file-scan-dir="$PHP_INI_DIR/conf.d" \
+		$PHP_EXTRA_CONFIGURE_ARGS \
+		--disable-cgi \
+		--enable-mysqlnd \
+		--with-curl \
+		--with-openssl \
+		--with-readline \
+		--with-recode \
+		--with-zlib \
+	&& make -j"$(nproc)" \
+	&& make install \
+	&& { find /usr/local/bin /usr/local/sbin -type f -executable -exec strip --strip-all '{}' + || true; } \
+	&& apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false -o APT::AutoRemove::SuggestsImportant=false $buildDeps \
+	&& make clean
+
+COPY docker-php-ext-* /usr/local/bin/
+
+COPY php-fpm.conf /usr/local/etc/
+
+EXPOSE 9000
+
+# Clean up APT when done.
+RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 RUN \
   mkdir -p /usr/local/bin \
   && cd /usr/local/bin \
   && php -r "readfile('https://getcomposer.org/installer');" | php \
   && mv composer.phar composer
+
+RUN mkdir /etc/service/php-fpm
+ADD php-fpm.sh /etc/service/php-fpm/run
+RUN chmod +x /etc/service/php-fpm/run
 
 WORKDIR /var/www
